# https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: snykcon-2020-deployment # name of my deployment
  annotations:
    container.apparmor.security.beta.kubernetes.io/snykcon-2020: runtime/default
spec:
  selector:
    matchLabels:
      app: snykcon-2020
  replicas: 2 # run two containers
  template:
    metadata:
      labels:
        app: snykcon-2020
    spec:
      containers:
        - name: snykcon-2020
          image: benlaplanche/snykcon-2020:latest # Docker Hub reference
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # port to run our container on
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            # runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - all
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: snykcon-2020-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 127.0.0.0/0 # where do we want to allow traffic from
  ports:
    - port: 8080 # port to expose externally
      targetPort: 8080
  selector:
    app: snykcon-2020 # application to bind to
