name: Snyk Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  snyk-kubernetes-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest file for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: deployment.yaml
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      - name: Snyk IaC Security Check
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          status: failure
          description: Failed Snyk IaC Security tests
          failComment: Failed Snyk IaC Security tests
          addHoldComment: Failed Snyk IaC
      # - if: always()
      #   uses: ouzi-dev/commit-status-updater@v1.1.0
      #   with:
      #     addHoldComment: "true"
      #     status: "${{ job.status }}"