name: Snyk Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  snyk-kubernetes-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest file for issues
        id: snyk-iac
        continue-on-error: false
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: deployment.yaml
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      - name: Update status as failed
        if: steps.snyk-iac.outcome == failure
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          status: failure
          description: Failed Snyk IaC Security tests
          failComment: Failed Snyk IaC Security tests
      - name: Update status as success
        if: steps.snyk-iac.outcome == success
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          status: success
          description: Passed Snyk IaC Security tests
          successComment: Passed Snyk IaC Security tests